package common

type UnsignedData struct {
	Age             int    `json:"age"`              // The time in milliseconds that has elapsed since the event was sent. This field is generated by the local homeserver, and may be incorrect if the local time on at least one of the two servers is out of sync, which can cause the age to either be negative or greater than it actually is.
	RedactedBecause Event  `json:"redacted_because"` // Optional. The event that redacted this event, if any.
	TransactionID   string `json:"transaction_id"`   // The client-supplied transaction ID, if the client being given the event is the same one which sent it.
}
